import { Project, LearningTrack, SkillCategory, VisionPhase } from './types';

export const LOGO_URL = "https://lh3.googleusercontent.com/aida/AEtjO1WvW9Q6BBxf5Rws_0ajg_c0iV6C_XCC7tdNIRjQ7AmpAtxf1x3f-CAVsHZokyB-lqUTeKi_KEcSynzsMr5usQrmupQLXIkbKJk5JdToLIoPDJ0U2vr0x48A6Xd2HQyGbSnhG-SIGFeD0Hgn9rTtbgbv7LRO-bCssEMfJ89Mc0NtL2a4X8A7s9H5Ed8qDd-9P3GJUfeJZ2XAnah1LA34U1Fo5iyhfh5GwM34iXooLbWN46dyRsnyeesRO7o";

export const PROJECTS: Project[] = [
  {
    id: 'project-1',
    code: 'PROJECT_01',
    tag: 'Upcoming Build',
    title: 'AI-Powered Knowledge & Reasoning Agent',
    category: 'Vector Search Pipeline • Python / FastAPI',
    description: 'An intelligent retrieval-augmented generation (RAG) agent capable of parsing dense academic or domain documentation into a semantic vector store, offering accurate contextual answers and source provenance.',
    fullOverview: 'Engineered to overcome LLM hallucinations in dense academic papers and technical specs. Features chunking with overlap, hybrid lexical-dense vector search, reranking with cross-encoders, and citations linked to document page coordinates.',
    stack: ['Python', 'Vector DB', 'FastAPI', 'LLM Orchestration', 'LangChain', 'ChromaDB'],
    specs: [
      { label: 'Embedding Model', value: 'bge-large-en-v1.5' },
      { label: 'Latency Target', value: '< 240ms end-to-end' },
      { label: 'Architecture', value: 'Multi-stage RAG with Cross-Encoder' },
      { label: 'Deployment', value: 'Docker container on AWS ECS' }
    ],
    architectureSummary: 'Ingestion Pipeline → Semantic Chunking → Embedding Matrix → Vector Index → Context Re-ranker → Synthesizer LLM → Citation Formatter',
    githubUrl: 'https://github.com',
    demoUrl: '#',
    diagramType: 'rag',
  },
  {
    id: 'project-2',
    code: 'PROJECT_02',
    tag: 'In Concept & Design',
    title: 'Algorithmic Market & Sentiment Intelligence',
    category: 'Sentiment Extraction Core • Python / NLP',
    description: 'A pipeline combining web scraping, natural language tokenization, and polarity scoring to detect real-time sentiment shifts across tech discussions and market news updates.',
    fullOverview: 'Automated ingestion pipeline parsing tech forums, financial news feeds, and developer discussion threads. Generates aggregated velocity curves and sentiment indicators for emerging technologies and startup niches.',
    stack: ['Python', 'ML Fundamentals', 'NLP', 'Streamlit', 'BeautifulSoup', 'Hugging Face'],
    specs: [
      { label: 'Data Ingestion', value: 'Async distributed scrapers' },
      { label: 'NLP Transformer', value: 'FinBERT fine-tuned' },
      { label: 'Refresh Rate', value: 'Real-time WebSocket streaming' },
      { label: 'Visualization', value: 'Interactive Streamlit & Plotly UI' }
    ],
    architectureSummary: 'Feed Collectors → Tokenization & Preprocessing → Transformer Sentiment Classification → Time-Series Smoothing → Trend Visualization',
    githubUrl: 'https://github.com',
    demoUrl: '#',
    diagramType: 'sparkline',
  },
  {
    id: 'project-3',
    code: 'PROJECT_03',
    tag: 'Under Prototyping',
    title: 'Interactive Computational Learning Canvas',
    category: 'Interactive Visuals • JavaScript / Python',
    description: 'An open educational web tool engineered to help computer science students visualize complex algorithmic transitions, pointer maneuvers, and graph traversals in real time.',
    fullOverview: 'A step-by-step graphical sandbox that renders data structures in memory. Students can single-step through recursion trees, red-black tree rebalancing, Dijkstra shortest paths, and memory pointer reassignments with playback scrubbers.',
    stack: ['Web Architecture', 'JavaScript', 'Python Backend', 'Canvas API', 'Tailwind CSS', 'WebSockets'],
    specs: [
      { label: 'Rendering Core', value: 'HTML5 2D Canvas + WebGL' },
      { label: 'Execution Mode', value: 'Client-side AST stepping' },
      { label: 'Algorithmic Coverage', value: 'Trees, Graphs, Sorting, DP' },
      { label: 'Interactivity', value: 'Drag-and-drop nodes with timeline' }
    ],
    architectureSummary: 'Code Parser → Abstract Execution Engine → State Diff Generator → Canvas Vector Renderer → Interactive Timeline Controls',
    githubUrl: 'https://github.com',
    demoUrl: '#',
    diagramType: 'nodes',
  },
];

export const LEARNING_TRACKS: LearningTrack[] = [
  {
    id: 'track-1',
    trackNumber: 'TRACK_01',
    tag: 'Active Focus',
    title: 'Advanced Data Structures & Algorithms',
    description: 'Algorithmic patterns, dynamic programming, tree traversals, and graphs. Systematic practice focused on spatial and computational efficiency.',
    focusText: 'Focus: LeetCode • Complexity Optimization',
    iconName: 'Network',
    accentColor: 'secondary',
  },
  {
    id: 'track-2',
    trackNumber: 'TRACK_02',
    tag: 'Active Focus',
    title: 'Advanced Python Engineering',
    description: 'Concurrency, asyncio, memory management, generators, metaclasses, and architecting robust, modular backends with clean typing.',
    focusText: 'Focus: Production Patterns • Asynchronous IO',
    iconName: 'Terminal',
    accentColor: 'primary',
  },
  {
    id: 'track-3',
    trackNumber: 'TRACK_03',
    tag: 'Active Focus',
    title: 'Machine Learning Systems',
    description: 'Deepening model training pipelines, supervised/unsupervised algorithms, neural network foundations, and evaluation metrics using PyTorch.',
    focusText: 'Focus: PyTorch • Pipeline Engineering',
    iconName: 'Cpu',
    accentColor: 'tertiary',
  },
  {
    id: 'track-4',
    trackNumber: 'TRACK_04',
    tag: 'Active Focus',
    title: 'Cloud Architecture (AWS)',
    description: 'Understanding cloud infrastructure fundamentals: EC2, S3, IAM, Lambda serverless, and provisioning scalable runtime environments for ML models.',
    focusText: 'Focus: AWS Compute, Storage & Deployment',
    iconName: 'Cloud',
    accentColor: 'secondary',
  },
  {
    id: 'track-5',
    trackNumber: 'TRACK_05',
    tag: 'Active Focus',
    title: 'Modern Full-Stack Integration',
    description: 'Connecting intelligent backend APIs with fast, responsive front-end interfaces to transform algorithmic engines into consumer-ready utilities.',
    focusText: 'Focus: REST APIs, FastAPI & UI Architecture',
    iconName: 'Layout',
    accentColor: 'primary',
  },
  {
    id: 'track-6',
    trackNumber: 'TRACK_06',
    tag: 'Active Focus',
    title: 'Tech & Finance Literacy',
    description: 'Studying fintech primitives, venture capital economics, quantitative basics, and engaging with technical developer communities.',
    focusText: 'Focus: FinTech Ecosystems & Community',
    iconName: 'Coins',
    accentColor: 'tertiary',
  },
];

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    title: 'Technical Foundation',
    subtitle: 'CORE STACK',
    skills: [
      'Python Programming',
      'OOP Principles',
      'DBMS Architecture',
      'MySQL / SQL',
      'Web Fundamentals (HTML/CSS/JS)',
      'Git & GitHub',
      'AI & ML Fundamentals',
      'Cloud Computing Basics',
    ],
    deepeningSkills: ['Data Structures & Algorithms (DSA)'],
    footerNote: 'Targeting computational efficiency',
    statusBadge: '• Active Drills',
    accentColor: 'secondary',
    iconName: 'Code',
  },
  {
    title: 'Problem Solving & Learning',
    subtitle: 'COGNITIVE TOOLS',
    description: 'The capability to parse abstract problems into modular sub-tasks, rapidly acquire domain concepts, and iterate toward clean solutions.',
    skills: [
      'Self-Directed Learning',
      'Rapid Skill Acquisition',
      'Analytical Problem Solving',
      'Systematic Debugging',
      'Deconstructing Unfamiliar Tech',
      'AI-Assisted Productivity Workflow',
      'Continuous Self-Reflection',
    ],
    footerNote: 'Meta-learning framework',
    statusBadge: '• Iterative Growth',
    accentColor: 'primary',
    iconName: 'BrainCircuit',
  },
  {
    title: 'Creative & Communication',
    subtitle: 'EXPRESSION',
    description: 'Balancing analytical rigor with creative synthesis: stage performance, storytelling, short-form media engagement, and compelling presentation.',
    skills: [
      'Dance & Rhythm Performance',
      'Short-Form Video / Reels',
      'Content Ideation & Curation',
      'Visual Presentation',
      'Personal Branding',
      'Social Communication',
      'Networking',
      'Visual Storytelling',
    ],
    footerNote: 'Creative poise & clarity',
    statusBadge: '• Multidisciplinary',
    accentColor: 'tertiary',
    iconName: 'Palette',
  },
  {
    title: 'Professional & Leadership',
    subtitle: 'VENTURE DRIVEN',
    description: 'Fostering an enterprise horizon: combining computational technologies with market dynamics, product leadership, and global career vision.',
    skills: [
      'Innovation Ideation',
      'Entrepreneurial Mindset',
      'Tech & Finance Interest',
      'Global Career Orientation',
      'Tech Venture Concepts',
      'Dynamic Adaptability',
      'Collaborative Alignment',
    ],
    footerNote: 'Building high-impact technology',
    statusBadge: '• Forward Vision',
    accentColor: 'secondary',
    iconName: 'TrendingUp',
  },
];

export const VISION_PHASES: VisionPhase[] = [
  {
    phaseNumber: '01 • PHASE',
    title: 'Learn',
    summary: 'Absorbing algorithms, systems design, and mathematical bedrock.',
    status: 'In Progress • Deep Focus',
    accentColor: 'secondary',
  },
  {
    phaseNumber: '02 • PHASE',
    title: 'Build',
    summary: 'Converting theory into reliable prototypes and verified codebases.',
    status: 'Active Iteration',
    accentColor: 'primary',
  },
  {
    phaseNumber: '03 • PHASE',
    title: 'Experiment',
    summary: 'Testing models, finding limits, and optimizing user workflows.',
    status: 'Continuous',
    accentColor: 'tertiary',
  },
  {
    phaseNumber: '04 • PHASE',
    title: 'Create',
    summary: 'Delivering full-stack AI applications that serve real-world needs.',
    status: 'Horizon Target',
    accentColor: 'primary',
  },
  {
    phaseNumber: '05 • PHASE',
    title: 'Lead',
    summary: 'Spearheading tech-focused ventures and high-performing engineering teams.',
    status: 'Long-Term Mission',
    accentColor: 'secondary',
  },
];
